--------------------------------------------------------
--  文件已创建 - 星期二-十二月-25-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COURSE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."COURSE" 
   (	"CNO" VARCHAR2(20 BYTE), 
	"CNAME" VARCHAR2(20 BYTE), 
	"CREDIT" NUMBER DEFAULT 0, 
	"TNO" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON COLUMN "SYSTEM"."COURSE"."CNO" IS '课程编号';
 
   COMMENT ON COLUMN "SYSTEM"."COURSE"."CNAME" IS '课程名称';
 
   COMMENT ON COLUMN "SYSTEM"."COURSE"."CREDIT" IS '学分';
 
   COMMENT ON COLUMN "SYSTEM"."COURSE"."TNO" IS '教师编号';
REM INSERTING into SYSTEM.COURSE
SET DEFINE OFF;
Insert into SYSTEM.COURSE (CNO,CNAME,CREDIT,TNO) values ('c1','Oracle数据库',2,'t1');
Insert into SYSTEM.COURSE (CNO,CNAME,CREDIT,TNO) values ('c2','操作系统',3,'t2');
Insert into SYSTEM.COURSE (CNO,CNAME,CREDIT,TNO) values ('c4','经济学',1,'t2');
Insert into SYSTEM.COURSE (CNO,CNAME,CREDIT,TNO) values ('c8','PHP',3,'t2');
Insert into SYSTEM.COURSE (CNO,CNAME,CREDIT,TNO) values ('c9','linux',5,'t3');
Insert into SYSTEM.COURSE (CNO,CNAME,CREDIT,TNO) values ('c7','移动应用开发23',2,'t3');
Insert into SYSTEM.COURSE (CNO,CNAME,CREDIT,TNO) values ('c10','编译原理',3,'t3');
Insert into SYSTEM.COURSE (CNO,CNAME,CREDIT,TNO) values ('c11','图像处理',2,'t2');
Insert into SYSTEM.COURSE (CNO,CNAME,CREDIT,TNO) values ('c12','计算方法',1,'t1');
Insert into SYSTEM.COURSE (CNO,CNAME,CREDIT,TNO) values ('c13','概率论',2,'t8');
Insert into SYSTEM.COURSE (CNO,CNAME,CREDIT,TNO) values ('c14','马克思理论',1,'t1');
--------------------------------------------------------
--  DDL for Index COURSE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."COURSE_PK" ON "SYSTEM"."COURSE" ("CNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table COURSE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."COURSE" ADD CONSTRAINT "COURSE_PK" PRIMARY KEY ("CNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."COURSE" MODIFY ("CNO" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."COURSE" MODIFY ("CNAME" NOT NULL ENABLE);
