--------------------------------------------------------
--  文件已创建 - 星期二-十二月-25-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table STUDENT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."STUDENT" 
   (	"SNO" VARCHAR2(20 BYTE), 
	"SNAME" VARCHAR2(20 BYTE), 
	"SSEX" VARCHAR2(20 BYTE), 
	"TC" NUMBER, 
	"SBIRTHDAY" DATE, 
	"SPECIALITY" VARCHAR2(20 BYTE), 
	"SCLASS" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE) DEFAULT '123456'
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON COLUMN "SYSTEM"."STUDENT"."SNO" IS '学号';
 
   COMMENT ON COLUMN "SYSTEM"."STUDENT"."SNAME" IS '名字';
 
   COMMENT ON COLUMN "SYSTEM"."STUDENT"."SSEX" IS '性别';
 
   COMMENT ON COLUMN "SYSTEM"."STUDENT"."TC" IS '总学分';
 
   COMMENT ON COLUMN "SYSTEM"."STUDENT"."SBIRTHDAY" IS '出生日期';
 
   COMMENT ON COLUMN "SYSTEM"."STUDENT"."SPECIALITY" IS '专业';
 
   COMMENT ON COLUMN "SYSTEM"."STUDENT"."SCLASS" IS '班号';
REM INSERTING into SYSTEM.STUDENT
SET DEFINE OFF;
Insert into SYSTEM.STUDENT (SNO,SNAME,SSEX,TC,SBIRTHDAY,SPECIALITY,SCLASS,PASSWORD) values ('1002','张锦坚','男',5,to_date('13-DEC-18','DD-MON-RR'),'软卓','1','123456');
Insert into SYSTEM.STUDENT (SNO,SNAME,SSEX,TC,SBIRTHDAY,SPECIALITY,SCLASS,PASSWORD) values ('1003','郑永荣','男',0,to_date('05-DEC-18','DD-MON-RR'),'软卓','1','123456');
Insert into SYSTEM.STUDENT (SNO,SNAME,SSEX,TC,SBIRTHDAY,SPECIALITY,SCLASS,PASSWORD) values ('1001','刘世杰','男',7,to_date('02-DEC-15','DD-MON-RR'),'软卓','2','123');
Insert into SYSTEM.STUDENT (SNO,SNAME,SSEX,TC,SBIRTHDAY,SPECIALITY,SCLASS,PASSWORD) values ('1004','公正','男',0,to_date('06-DEC-18','DD-MON-RR'),'软卓','888','123456');
Insert into SYSTEM.STUDENT (SNO,SNAME,SSEX,TC,SBIRTHDAY,SPECIALITY,SCLASS,PASSWORD) values ('1005','学生1','女',0,to_date('24-DEC-18','DD-MON-RR'),'软工','1','123456');
Insert into SYSTEM.STUDENT (SNO,SNAME,SSEX,TC,SBIRTHDAY,SPECIALITY,SCLASS,PASSWORD) values ('1006','学生2','女',0,to_date('24-DEC-18','DD-MON-RR'),'软工','2','123456');
Insert into SYSTEM.STUDENT (SNO,SNAME,SSEX,TC,SBIRTHDAY,SPECIALITY,SCLASS,PASSWORD) values ('1007','学生3','女',0,to_date('24-DEC-18','DD-MON-RR'),'软工','2','123456');
Insert into SYSTEM.STUDENT (SNO,SNAME,SSEX,TC,SBIRTHDAY,SPECIALITY,SCLASS,PASSWORD) values ('1008','学生4','女',0,to_date('24-DEC-18','DD-MON-RR'),'软工','2','123456');
Insert into SYSTEM.STUDENT (SNO,SNAME,SSEX,TC,SBIRTHDAY,SPECIALITY,SCLASS,PASSWORD) values ('1009','学生5','女',0,to_date('24-DEC-18','DD-MON-RR'),'软工','2','123456');
Insert into SYSTEM.STUDENT (SNO,SNAME,SSEX,TC,SBIRTHDAY,SPECIALITY,SCLASS,PASSWORD) values ('1010','学生6','男',0,to_date('24-DEC-18','DD-MON-RR'),'软工','2','123456');
Insert into SYSTEM.STUDENT (SNO,SNAME,SSEX,TC,SBIRTHDAY,SPECIALITY,SCLASS,PASSWORD) values ('1011','学生7','女',0,to_date('24-DEC-18','DD-MON-RR'),'软工','2','123456');
Insert into SYSTEM.STUDENT (SNO,SNAME,SSEX,TC,SBIRTHDAY,SPECIALITY,SCLASS,PASSWORD) values ('1012','学生8','女',0,to_date('24-DEC-18','DD-MON-RR'),'软工','2','123456');
Insert into SYSTEM.STUDENT (SNO,SNAME,SSEX,TC,SBIRTHDAY,SPECIALITY,SCLASS,PASSWORD) values ('1013','学生10086','男',0,to_date('02-DEC-18','DD-MON-RR'),'软工','2','123456');
Insert into SYSTEM.STUDENT (SNO,SNAME,SSEX,TC,SBIRTHDAY,SPECIALITY,SCLASS,PASSWORD) values ('1014','学生666','男',0,to_date('17-DEC-18','DD-MON-RR'),'软卓','12','123456');
Insert into SYSTEM.STUDENT (SNO,SNAME,SSEX,TC,SBIRTHDAY,SPECIALITY,SCLASS,PASSWORD) values ('1015','哒哒哒','男',0,to_date('06-JUN-18','DD-MON-RR'),'软卓','1','123456');
--------------------------------------------------------
--  DDL for Index STUDENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."STUDENT_PK" ON "SYSTEM"."STUDENT" ("SNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table STUDENT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."STUDENT" ADD CONSTRAINT "STUDENT_PK" PRIMARY KEY ("SNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."STUDENT" MODIFY ("SNO" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."STUDENT" MODIFY ("SNAME" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."STUDENT" MODIFY ("SSEX" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."STUDENT" MODIFY ("SBIRTHDAY" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."STUDENT" MODIFY ("PASSWORD" NOT NULL ENABLE);
